dist: 'dist'
entrypoint: 'index.js'
tasks:
  scripts: 'runkit-scripts'
  eslint: 'runkit-eslint'
  watcher: 'runkit-watcher'
  default:
    -
      - 'eslint'
      - 'scripts'
  dev:
    - 'watcher'
scripts:
  browserify:
    standalone: '{{libraryName}}'
  files: '{{scriptFiles}}'
watcher:
  ignore:
    - '{{dist}}'
    - 'node_modules'
  files:
    './**/*.js': 'default'
