dist: 'dist'
entrypoint: 'index.js'
tasks:
  scripts: 'runkit-scripts'
  eslint: 'runkit-eslint'
  watcher: 'runkit-watcher'
  livereload: 'runkit-livereload'
  default:
    -
      - 'eslint'
      - 'scripts'
  dev:
    - 'livereload'
    - 'watcher'
scripts:
  browserify:
    standalone: '{{libraryName}}'
  files: '{{scriptFiles}}'
watcher:
  ignore:
    - '{{dist}}'
    - 'node_modules'
  files:
    './**/*.js': 
      task: 'default'
      ignore: 
        - '{{dist}}'
    '{{dist}}/*': 'livereload'
