dist: 'dist'
entrypoint: 'index.js'
libraryName: '{{getEnv("TASKKIT_LIBNAME")}}'
crashOnError: true
tasks:
  test: 'taskkit-shell'
  serve: 'taskkit-shell'
  scripts: 'taskkit-rollup'
  eslint: 'taskkit-eslint'
  watcher: 'taskkit-watcher'
  livereload: 'taskkit-livereload'
  clean: 'taskkit-clean'
  analyze: 'taskkit-analyze'
  default:
    - 'build'
    - 'test'
    - 'analyze'
  build:
    - 'clean'
    -
      - 'eslint'
      - 'scripts'
  dev:
    - 'build'
    - 'serve'
    - 'watcher'
scripts:
  rollup:
    bundle:
      name: '{{libraryName}}'
  commonjs:
    enabled: true
  globals: true
  builtins: true
  files: '{{files}}'
test:
  command: 'npm'
  args: 'test'
  timeout: '{{ 1000 * 20 }}' #timeout after 20 seconds
serve:
  enabled: false
  command: 'serve'
  continue: true
  args:
    p: 8080
    c: 0
  env:
    PATH: '{{ENV.PATH}}:{{CWD}}/node_modules/.bin'
livereload:
  enabled: false
clean:
  files:
    - '{{dist}}'
eslint:
  ignore:
    - '{{dist}}'
    - 'node_modules'
    - '.git'
    - '*.dist.*'
  files:
    - './**/*.js'

watcher:
  ignore:
    - 'node_modules'
    - '.git'
  files:
    './**/*.js':
      task: 'default'
      ignore:
        - '{{dist}}'
analyze:
  files: '{{files}}'
