dist: 'dist'
entrypoint: 'index.js'
tasks:
  test: 'taskkit-shell'
  scripts: 'taskkit-rollup'
  eslint: 'taskkit-eslint'
  watcher: 'taskkit-watcher'
  livereload: 'taskkit-livereload'
  clean: 'taskkit-clean'
  default:
    - 'build'
    - 'test'
  build:
    - 'clean'
    -
      - 'eslint'
      - 'scripts'
  dev:
    - 'livereload'
    - 'watcher'
scripts:
  name: '{{libraryName}}'
test:
  command: 'npm'
  arguments: 'test'
clean:
  files:
    - '{{dist}}'
eslint:
  ignore:
    - '{{dist}}'
    - 'node_modules'
    - '.git'
    - '*.dist.js'
  files:
    - './**/*.js'

watcher:
  ignore:
    - 'node_modules'
    - '.git'
  files:
    './**/*.js': 
      task: 'default'
      ignore: 
        - '{{dist}}'
    '{{dist}}/*': 'livereload'
